const mongoose = require("mongoose");
const dotenv = require("dotenv");
const Product = require("../models/Product");
const User = require("../models/User");

dotenv.config();

const placeholderImage = (text) =>
  `https://via.placeholder.com/500x500.png?text=${encodeURIComponent(text)}`;

const products = [
  // =========================
  // PACKED MASALA PRODUCTS
  // =========================
  {
    name: "Kachori Atta 400g",
    description: "Amrit Dayal Food Kachori Atta 400g",
    price: 85,
    mrp: 85,
    category: "Special Masala",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "400g",
    imageUrl: placeholderImage("Kachori Atta 400g"),
    isFeatured: true,
  },
  {
    name: "Kalaungi Masala 100g",
    description: "Amrit Dayal Food Kalaungi Masala 100g",
    price: 75,
    mrp: 75,
    category: "Special Masala",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "100g",
    imageUrl: placeholderImage("Kalaungi Masala 100g"),
    isFeatured: true,
  },
  {
    name: "Hing Pouch 50g",
    description: "Amrit Dayal Food Hing Pouch 50g",
    price: 98,
    mrp: 98,
    category: "Dry Spices",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "50g",
    imageUrl: placeholderImage("Hing Pouch 50g"),
    isFeatured: true,
  },
  {
    name: "Hing Premium Box",
    description: "Amrit Dayal Food Hing Premium Box",
    price: 165,
    mrp: 165,
    category: "Dry Spices",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "Premium Box",
    imageUrl: placeholderImage("Hing Premium Box"),
    isFeatured: true,
  },
  {
    name: "Garam Masala 200g",
    description: "Amrit Dayal Food Garam Masala 200g",
    price: 155,
    mrp: 155,
    category: "Powder Masala",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "200g",
    imageUrl: placeholderImage("Garam Masala 200g"),
    isFeatured: true,
  },
  {
    name: "Garam Masala 500g",
    description: "Amrit Dayal Food Garam Masala 500g",
    price: 495,
    mrp: 495,
    category: "Powder Masala",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "500g",
    imageUrl: placeholderImage("Garam Masala 500g"),
    isFeatured: false,
  },
  {
    name: "Haldi 200g",
    description: "Amrit Dayal Food Haldi 200g",
    price: 85,
    mrp: 85,
    category: "Powder Masala",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "200g",
    imageUrl: placeholderImage("Haldi 200g"),
    isFeatured: true,
  },
  {
    name: "Haldi 500g",
    description: "Amrit Dayal Food Haldi 500g",
    price: 210,
    mrp: 210,
    category: "Powder Masala",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "500g",
    imageUrl: placeholderImage("Haldi 500g"),
    isFeatured: false,
  },
  {
    name: "Mirch Powder 200g",
    description: "Amrit Dayal Food Mirch Powder 200g",
    price: 110,
    mrp: 110,
    category: "Powder Masala",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "200g",
    imageUrl: placeholderImage("Mirch Powder 200g"),
    isFeatured: true,
  },
  {
    name: "Mirch Powder 500g",
    description: "Amrit Dayal Food Mirch Powder 500g",
    price: 305,
    mrp: 305,
    category: "Powder Masala",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "500g",
    imageUrl: placeholderImage("Mirch Powder 500g"),
    isFeatured: false,
  },
  {
    name: "Dhaniya Powder 200g",
    description: "Amrit Dayal Food Dhaniya Powder 200g",
    price: 75,
    mrp: 75,
    category: "Powder Masala",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "200g",
    imageUrl: placeholderImage("Dhaniya Powder 200g"),
    isFeatured: true,
  },
  {
    name: "Dhaniya Powder 500g",
    description: "Amrit Dayal Food Dhaniya Powder 500g",
    price: 195,
    mrp: 195,
    category: "Powder Masala",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "500g",
    imageUrl: placeholderImage("Dhaniya Powder 500g"),
    isFeatured: false,
  },
  {
    name: "Khada Masala 50g",
    description: "Amrit Dayal Food Khada Masala 50g",
    price: 110,
    mrp: 110,
    category: "Whole Spices",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "50g",
    imageUrl: placeholderImage("Khada Masala 50g"),
    isFeatured: true,
  },
  {
    name: "Khada Masala 100g",
    description: "Amrit Dayal Food Khada Masala 100g",
    price: 210,
    mrp: 210,
    category: "Whole Spices",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "100g",
    imageUrl: placeholderImage("Khada Masala 100g"),
    isFeatured: false,
  },
  {
    name: "Khada Masala 250g",
    description: "Amrit Dayal Food Khada Masala 250g",
    price: 510,
    mrp: 510,
    category: "Whole Spices",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "250g",
    imageUrl: placeholderImage("Khada Masala 250g"),
    isFeatured: false,
  },
  {
    name: "Sabzi Masala 100g",
    description: "Amrit Dayal Food Sabzi Masala 100g",
    price: 77,
    mrp: 77,
    category: "Special Masala",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "100g",
    imageUrl: placeholderImage("Sabzi Masala 100g"),
    isFeatured: true,
  },
  {
    name: "Sabzi Masala 500g",
    description: "Amrit Dayal Food Sabzi Masala 500g",
    price: 295,
    mrp: 295,
    category: "Special Masala",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "500g",
    imageUrl: placeholderImage("Sabzi Masala 500g"),
    isFeatured: false,
  },
  {
    name: "Kali Mirch Powder 100g",
    description: "Amrit Dayal Food Kali Mirch Powder 100g",
    price: 195,
    mrp: 195,
    category: "Powder Masala",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "100g",
    imageUrl: placeholderImage("Kali Mirch Powder 100g"),
    isFeatured: true,
  },
  {
    name: "Bhuna Jeera Powder 100g",
    description: "Amrit Dayal Food Bhuna Jeera Powder 100g",
    price: 129,
    mrp: 129,
    category: "Powder Masala",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "100g",
    imageUrl: placeholderImage("Bhuna Jeera Powder 100g"),
    isFeatured: true,
  },
  {
    name: "Chat Masala 200g",
    description: "Amrit Dayal Food Chat Masala 200g",
    price: 155,
    mrp: 155,
    category: "Special Masala",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "200g",
    imageUrl: placeholderImage("Chat Masala 200g"),
    isFeatured: true,
  },
  {
    name: "Chat Masala 500g",
    description: "Amrit Dayal Food Chat Masala 500g",
    price: 265,
    mrp: 265,
    category: "Special Masala",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "500g",
    imageUrl: placeholderImage("Chat Masala 500g"),
    isFeatured: false,
  },
  {
    name: "Safed Mirch Powder 100g",
    description: "Amrit Dayal Food Safed Mirch Powder 100g",
    price: 230,
    mrp: 230,
    category: "Powder Masala",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "100g",
    imageUrl: placeholderImage("Safed Mirch Powder 100g"),
    isFeatured: true,
  },

  // =========================
  // WHOLE SPICES PRODUCTS
  // =========================
  {
    name: "Jeera 50g",
    description: "Amrit Dayal Food Jeera 50g",
    price: 42,
    mrp: 42,
    category: "Whole Spices",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "50g",
    imageUrl: placeholderImage("Jeera 50g"),
    isFeatured: true,
  },
  {
    name: "Jeera 100g",
    description: "Amrit Dayal Food Jeera 100g",
    price: 78,
    mrp: 78,
    category: "Whole Spices",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "100g",
    imageUrl: placeholderImage("Jeera 100g"),
    isFeatured: false,
  },
  {
    name: "Jeera 200g",
    description: "Amrit Dayal Food Jeera 200g",
    price: 152,
    mrp: 152,
    category: "Whole Spices",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "200g",
    imageUrl: placeholderImage("Jeera 200g"),
    isFeatured: false,
  },
  {
    name: "Dhania Whole 50g",
    description: "Amrit Dayal Food Dhania Whole 50g",
    price: 25,
    mrp: 25,
    category: "Whole Spices",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "50g",
    imageUrl: placeholderImage("Dhania Whole 50g"),
    isFeatured: true,
  },
  {
    name: "Dhania Whole 100g",
    description: "Amrit Dayal Food Dhania Whole 100g",
    price: 39,
    mrp: 39,
    category: "Whole Spices",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "100g",
    imageUrl: placeholderImage("Dhania Whole 100g"),
    isFeatured: false,
  },
  {
    name: "Dhania Whole 200g",
    description: "Amrit Dayal Food Dhania Whole 200g",
    price: 75,
    mrp: 75,
    category: "Whole Spices",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "200g",
    imageUrl: placeholderImage("Dhania Whole 200g"),
    isFeatured: false,
  },
  {
    name: "Saunf 50g",
    description: "Amrit Dayal Food Saunf 50g",
    price: 37,
    mrp: 37,
    category: "Seeds",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "50g",
    imageUrl: placeholderImage("Saunf 50g"),
    isFeatured: true,
  },
  {
    name: "Saunf 100g",
    description: "Amrit Dayal Food Saunf 100g",
    price: 65,
    mrp: 65,
    category: "Seeds",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "100g",
    imageUrl: placeholderImage("Saunf 100g"),
    isFeatured: false,
  },
  {
    name: "Saunf 200g",
    description: "Amrit Dayal Food Saunf 200g",
    price: 94,
    mrp: 94,
    category: "Seeds",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "200g",
    imageUrl: placeholderImage("Saunf 200g"),
    isFeatured: false,
  },
  {
    name: "Kali Mirch Whole 25g",
    description: "Amrit Dayal Food Kali Mirch Whole 25g",
    price: 45,
    mrp: 45,
    category: "Whole Spices",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "25g",
    imageUrl: placeholderImage("Kali Mirch Whole 25g"),
    isFeatured: true,
  },
  {
    name: "Kali Mirch Whole 50g",
    description: "Amrit Dayal Food Kali Mirch Whole 50g",
    price: 81,
    mrp: 81,
    category: "Whole Spices",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "50g",
    imageUrl: placeholderImage("Kali Mirch Whole 50g"),
    isFeatured: false,
  },
  {
    name: "Kali Mirch Whole 100g",
    description: "Amrit Dayal Food Kali Mirch Whole 100g",
    price: 154,
    mrp: 154,
    category: "Whole Spices",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "100g",
    imageUrl: placeholderImage("Kali Mirch Whole 100g"),
    isFeatured: false,
  },
  {
    name: "Kali Mirch Whole 200g",
    description: "Amrit Dayal Food Kali Mirch Whole 200g",
    price: 295,
    mrp: 295,
    category: "Whole Spices",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "200g",
    imageUrl: placeholderImage("Kali Mirch Whole 200g"),
    isFeatured: false,
  },
  {
    name: "Clove 25g",
    description: "Amrit Dayal Food Clove 25g",
    price: 59,
    mrp: 59,
    category: "Whole Spices",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "25g",
    imageUrl: placeholderImage("Clove 25g"),
    isFeatured: true,
  },
  {
    name: "Clove 50g",
    description: "Amrit Dayal Food Clove 50g",
    price: 115,
    mrp: 115,
    category: "Whole Spices",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "50g",
    imageUrl: placeholderImage("Clove 50g"),
    isFeatured: false,
  },
  {
    name: "Clove 100g",
    description: "Amrit Dayal Food Clove 100g",
    price: 225,
    mrp: 225,
    category: "Whole Spices",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "100g",
    imageUrl: placeholderImage("Clove 100g"),
    isFeatured: false,
  },
  {
    name: "Clove 200g",
    description: "Amrit Dayal Food Clove 200g",
    price: 440,
    mrp: 440,
    category: "Whole Spices",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "200g",
    imageUrl: placeholderImage("Clove 200g"),
    isFeatured: false,
  },
  {
    name: "Badi Ilaichi 25g",
    description: "Amrit Dayal Food Badi Ilaichi 25g",
    price: 112,
    mrp: 112,
    category: "Whole Spices",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "25g",
    imageUrl: placeholderImage("Badi Ilaichi 25g"),
    isFeatured: true,
  },
  {
    name: "Badi Ilaichi 50g",
    description: "Amrit Dayal Food Badi Ilaichi 50g",
    price: 215,
    mrp: 215,
    category: "Whole Spices",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "50g",
    imageUrl: placeholderImage("Badi Ilaichi 50g"),
    isFeatured: false,
  },
  {
    name: "Badi Ilaichi 100g",
    description: "Amrit Dayal Food Badi Ilaichi 100g",
    price: 415,
    mrp: 415,
    category: "Whole Spices",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "100g",
    imageUrl: placeholderImage("Badi Ilaichi 100g"),
    isFeatured: false,
  },
  {
    name: "Badi Ilaichi 200g",
    description: "Amrit Dayal Food Badi Ilaichi 200g",
    price: 815,
    mrp: 815,
    category: "Whole Spices",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "200g",
    imageUrl: placeholderImage("Badi Ilaichi 200g"),
    isFeatured: false,
  },
  {
    name: "Choti Ilaichi 25g",
    description: "Amrit Dayal Food Choti Ilaichi 25g",
    price: 155,
    mrp: 155,
    category: "Whole Spices",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "25g",
    imageUrl: placeholderImage("Choti Ilaichi 25g"),
    isFeatured: true,
  },
  {
    name: "Choti Ilaichi 50g",
    description: "Amrit Dayal Food Choti Ilaichi 50g",
    price: 295,
    mrp: 295,
    category: "Whole Spices",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "50g",
    imageUrl: placeholderImage("Choti Ilaichi 50g"),
    isFeatured: false,
  },
  {
    name: "Choti Ilaichi 100g",
    description: "Amrit Dayal Food Choti Ilaichi 100g",
    price: 575,
    mrp: 575,
    category: "Whole Spices",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "100g",
    imageUrl: placeholderImage("Choti Ilaichi 100g"),
    isFeatured: false,
  },
  {
    name: "Jaifal 3 pcs",
    description: "Amrit Dayal Food Jaifal 3 pcs",
    price: 27,
    mrp: 27,
    category: "Whole Spices",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "pcs",
    weight: "3 pcs",
    imageUrl: placeholderImage("Jaifal 3 pcs"),
    isFeatured: true,
  },
  {
    name: "Jaifal 6 pcs",
    description: "Amrit Dayal Food Jaifal 6 pcs",
    price: 52,
    mrp: 52,
    category: "Whole Spices",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "pcs",
    weight: "6 pcs",
    imageUrl: placeholderImage("Jaifal 6 pcs"),
    isFeatured: false,
  },
  {
    name: "Star Phool 25g",
    description: "Amrit Dayal Food Star Phool 25g",
    price: 54,
    mrp: 54,
    category: "Whole Spices",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "25g",
    imageUrl: placeholderImage("Star Phool 25g"),
    isFeatured: true,
  },
  {
    name: "Star Phool 50g",
    description: "Amrit Dayal Food Star Phool 50g",
    price: 103,
    mrp: 103,
    category: "Whole Spices",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "50g",
    imageUrl: placeholderImage("Star Phool 50g"),
    isFeatured: false,
  },
  {
    name: "Shah Jeera 25g",
    description: "Amrit Dayal Food Shah Jeera 25g",
    price: 46,
    mrp: 46,
    category: "Whole Spices",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "25g",
    imageUrl: placeholderImage("Shah Jeera 25g"),
    isFeatured: true,
  },
  {
    name: "Shah Jeera 50g",
    description: "Amrit Dayal Food Shah Jeera 50g",
    price: 85,
    mrp: 85,
    category: "Whole Spices",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "50g",
    imageUrl: placeholderImage("Shah Jeera 50g"),
    isFeatured: false,
  },
  {
    name: "Javitri 25g",
    description: "Amrit Dayal Food Javitri 25g",
    price: 154,
    mrp: 154,
    category: "Whole Spices",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "25g",
    imageUrl: placeholderImage("Javitri 25g"),
    isFeatured: true,
  },
  {
    name: "Javitri 50g",
    description: "Amrit Dayal Food Javitri 50g",
    price: 299,
    mrp: 299,
    category: "Whole Spices",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "50g",
    imageUrl: placeholderImage("Javitri 50g"),
    isFeatured: false,
  },
  {
    name: "Bay Leaf 50g",
    description: "Amrit Dayal Food Bay Leaf 50g",
    price: 28,
    mrp: 28,
    category: "Whole Spices",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "50g",
    imageUrl: placeholderImage("Bay Leaf 50g"),
    isFeatured: true,
  },
  {
    name: "Bay Leaf 100g",
    description: "Amrit Dayal Food Bay Leaf 100g",
    price: 53,
    mrp: 53,
    category: "Whole Spices",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "100g",
    imageUrl: placeholderImage("Bay Leaf 100g"),
    isFeatured: false,
  },
  {
    name: "Bay Leaf 200g",
    description: "Amrit Dayal Food Bay Leaf 200g",
    price: 102,
    mrp: 102,
    category: "Whole Spices",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "200g",
    imageUrl: placeholderImage("Bay Leaf 200g"),
    isFeatured: false,
  },
  {
    name: "Pachfodan 50g",
    description: "Amrit Dayal Food Pachfodan 50g",
    price: 44,
    mrp: 44,
    category: "Whole Spices",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "50g",
    imageUrl: placeholderImage("Pachfodan 50g"),
    isFeatured: true,
  },
  {
    name: "Pachfodan 100g",
    description: "Amrit Dayal Food Pachfodan 100g",
    price: 82,
    mrp: 82,
    category: "Whole Spices",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "100g",
    imageUrl: placeholderImage("Pachfodan 100g"),
    isFeatured: false,
  },
  {
    name: "Kabab Chini 25g",
    description: "Amrit Dayal Food Kabab Chini 25g",
    price: 72,
    mrp: 72,
    category: "Whole Spices",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "25g",
    imageUrl: placeholderImage("Kabab Chini 25g"),
    isFeatured: true,
  },
  {
    name: "Kabab Chini 50g",
    description: "Amrit Dayal Food Kabab Chini 50g",
    price: 141,
    mrp: 141,
    category: "Whole Spices",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "50g",
    imageUrl: placeholderImage("Kabab Chini 50g"),
    isFeatured: false,
  },
  {
    name: "Safed Gol Mirch 25g",
    description: "Amrit Dayal Food Safed Gol Mirch 25g",
    price: 55,
    mrp: 55,
    category: "Whole Spices",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "25g",
    imageUrl: placeholderImage("Safed Gol Mirch 25g"),
    isFeatured: true,
  },
  {
    name: "Safed Gol Mirch 50g",
    description: "Amrit Dayal Food Safed Gol Mirch 50g",
    price: 113,
    mrp: 113,
    category: "Whole Spices",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "50g",
    imageUrl: placeholderImage("Safed Gol Mirch 50g"),
    isFeatured: false,
  },
  {
    name: "Ajwain 50g",
    description: "Amrit Dayal Food Ajwain 50g",
    price: 35,
    mrp: 35,
    category: "Seeds",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "50g",
    imageUrl: placeholderImage("Ajwain 50g"),
    isFeatured: true,
  },
  {
    name: "Ajwain 100g",
    description: "Amrit Dayal Food Ajwain 100g",
    price: 68,
    mrp: 68,
    category: "Seeds",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "100g",
    imageUrl: placeholderImage("Ajwain 100g"),
    isFeatured: false,
  },
  {
    name: "Ajwain 200g",
    description: "Amrit Dayal Food Ajwain 200g",
    price: 129,
    mrp: 129,
    category: "Seeds",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "200g",
    imageUrl: placeholderImage("Ajwain 200g"),
    isFeatured: false,
  },
  {
    name: "Mangrail 25g",
    description: "Amrit Dayal Food Mangrail 25g",
    price: 24,
    mrp: 24,
    category: "Seeds",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "25g",
    imageUrl: placeholderImage("Mangrail 25g"),
    isFeatured: true,
  },
  {
    name: "Mangrail 50g",
    description: "Amrit Dayal Food Mangrail 50g",
    price: 39,
    mrp: 39,
    category: "Seeds",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "50g",
    imageUrl: placeholderImage("Mangrail 50g"),
    isFeatured: false,
  },
  {
    name: "Mangrail 100g",
    description: "Amrit Dayal Food Mangrail 100g",
    price: 75,
    mrp: 75,
    category: "Seeds",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "100g",
    imageUrl: placeholderImage("Mangrail 100g"),
    isFeatured: false,
  },
  {
    name: "Mangrail 200g",
    description: "Amrit Dayal Food Mangrail 200g",
    price: 145,
    mrp: 145,
    category: "Seeds",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "200g",
    imageUrl: placeholderImage("Mangrail 200g"),
    isFeatured: false,
  },
  {
    name: "Methi 50g",
    description: "Amrit Dayal Food Methi 50g",
    price: 24,
    mrp: 24,
    category: "Seeds",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "50g",
    imageUrl: placeholderImage("Methi 50g"),
    isFeatured: true,
  },
  {
    name: "Methi 100g",
    description: "Amrit Dayal Food Methi 100g",
    price: 45,
    mrp: 45,
    category: "Seeds",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "100g",
    imageUrl: placeholderImage("Methi 100g"),
    isFeatured: false,
  },
  {
    name: "Rai 25g",
    description: "Amrit Dayal Food Rai 25g",
    price: 18,
    mrp: 18,
    category: "Seeds",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "25g",
    imageUrl: placeholderImage("Rai 25g"),
    isFeatured: true,
  },
  {
    name: "Rai 50g",
    description: "Amrit Dayal Food Rai 50g",
    price: 27,
    mrp: 27,
    category: "Seeds",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "50g",
    imageUrl: placeholderImage("Rai 50g"),
    isFeatured: false,
  },
  {
    name: "Rai 100g",
    description: "Amrit Dayal Food Rai 100g",
    price: 49,
    mrp: 49,
    category: "Seeds",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "100g",
    imageUrl: placeholderImage("Rai 100g"),
    isFeatured: false,
  },
  {
    name: "Mishrit Khada Masala 50g",
    description: "Amrit Dayal Food Mishrit Khada Masala 50g",
    price: 105,
    mrp: 105,
    category: "Whole Spices",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "50g",
    imageUrl: placeholderImage("Mishrit Khada Masala 50g"),
    isFeatured: true,
  },
  {
    name: "Mishrit Khada Masala 100g",
    description: "Amrit Dayal Food Mishrit Khada Masala 100g",
    price: 195,
    mrp: 195,
    category: "Whole Spices",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "100g",
    imageUrl: placeholderImage("Mishrit Khada Masala 100g"),
    isFeatured: false,
  },
  {
    name: "Posto Dana 25g",
    description: "Amrit Dayal Food Posto Dana 25g",
    price: 82,
    mrp: 82,
    category: "Seeds",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "25g",
    imageUrl: placeholderImage("Posto Dana 25g"),
    isFeatured: true,
  },
  {
    name: "Posto Dana 50g",
    description: "Amrit Dayal Food Posto Dana 50g",
    price: 158,
    mrp: 158,
    category: "Seeds",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "50g",
    imageUrl: placeholderImage("Posto Dana 50g"),
    isFeatured: false,
  },
  {
    name: "Posto Dana 100g",
    description: "Amrit Dayal Food Posto Dana 100g",
    price: 305,
    mrp: 305,
    category: "Seeds",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "100g",
    imageUrl: placeholderImage("Posto Dana 100g"),
    isFeatured: false,
  },
  {
    name: "Saunf Mahin 50g",
    description: "Amrit Dayal Food Saunf Mahin 50g",
    price: 45,
    mrp: 45,
    category: "Seeds",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "50g",
    imageUrl: placeholderImage("Saunf Mahin 50g"),
    isFeatured: true,
  },
  {
    name: "Saunf Mahin 100g",
    description: "Amrit Dayal Food Saunf Mahin 100g",
    price: 88,
    mrp: 88,
    category: "Seeds",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "100g",
    imageUrl: placeholderImage("Saunf Mahin 100g"),
    isFeatured: false,
  },
  {
    name: "Saunf Mahin 250g",
    description: "Amrit Dayal Food Saunf Mahin 250g",
    price: 210,
    mrp: 210,
    category: "Seeds",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "250g",
    imageUrl: placeholderImage("Saunf Mahin 250g"),
    isFeatured: false,
  },
  {
    name: "Safed Mirch Powder Premium 100g",
    description: "Amrit Dayal Food Safed Mirch Powder Premium 100g",
    price: 255,
    mrp: 255,
    category: "Powder Masala",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "100g",
    imageUrl: placeholderImage("Safed Mirch Powder Premium 100g"),
    isFeatured: true,
  },
  {
    name: "Yellow Mustard 50g",
    description: "Amrit Dayal Food Yellow Mustard 50g",
    price: 18,
    mrp: 18,
    category: "Seeds",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "50g",
    imageUrl: placeholderImage("Yellow Mustard 50g"),
    isFeatured: true,
  },
  {
    name: "Yellow Mustard 100g",
    description: "Amrit Dayal Food Yellow Mustard 100g",
    price: 28,
    mrp: 28,
    category: "Seeds",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "100g",
    imageUrl: placeholderImage("Yellow Mustard 100g"),
    isFeatured: false,
  },
  {
    name: "Black Mustard 50g",
    description: "Amrit Dayal Food Black Mustard 50g",
    price: 21,
    mrp: 21,
    category: "Seeds",
    brand: "Amrit Dayal Food",
    stock: 50,
    unit: "g",
    weight: "50g",
    imageUrl: placeholderImage("Black Mustard 50g"),
    isFeatured: true,
  },
];

const normalizeProduct = (product) => {
  const allowedUnits = ["kg", "g", "ltr", "ml", "pcs"];
  const fixedUnit = allowedUnits.includes(product.unit) ? product.unit : "g";

  return {
    ...product,
    unit: fixedUnit,
  };
};

const connectDB = async () => {
  try {
    const mongoUri =
      process.env.MONGODB_URI ||
      process.env.MONGO_URI ||
      process.env.DATABASE_URL ||
      process.env.DB_URI;

    if (!mongoUri) {
      console.error("MongoDB URI not found in .env file");
      console.error("Add MONGODB_URI or MONGO_URI in your .env file");
      process.exit(1);
    }

    await mongoose.connect(mongoUri);

    console.log("MongoDB connected for seeding");
    console.log("Database name:", mongoose.connection.name);
  } catch (error) {
    console.error("MongoDB connection failed:", error.message);
    process.exit(1);
  }
};

const importData = async () => {
  try {
    await connectDB();

    let creatorUser = await User.findOne({ role: "admin" });

    if (!creatorUser) {
      creatorUser = await User.findOne({});
    }

    const fixedProducts = products.map(normalizeProduct);

    let productsToInsert;

    if (creatorUser) {
      productsToInsert = fixedProducts.map((product) => ({
        ...product,
        createdBy: creatorUser._id,
      }));

      console.log(`Products will be created by: ${creatorUser.email}`);
    } else {
      productsToInsert = fixedProducts.map((product) => ({
        ...product,
      }));

      console.log(
        "No user found. Products will be inserted without createdBy.",
      );
    }

    await Product.deleteMany({});
    await Product.insertMany(productsToInsert);

    console.log(`${products.length} products imported successfully`);
    process.exit(0);
  } catch (error) {
    console.error("Seeder Error:", error);
    process.exit(1);
  }
};

const destroyData = async () => {
  try {
    await connectDB();

    await Product.deleteMany({});

    console.log("Products deleted successfully");
    process.exit(0);
  } catch (error) {
    console.error("Seeder Delete Error:", error);
    process.exit(1);
  }
};

if (process.argv[2] === "-d") {
  destroyData();
} else {
  importData();
}
